package com.alex.myexpenses.general;

import java.time.LocalDateTime;
import java.util.Map;

import org.springframework.http.HttpStatus;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO representing error information in case of validation or processing
 * issues.
 * <p>
 * This class holds a general error message and a collection of specific
 * field-level errors (e.g., input validation errors), mapping field names to
 * their associated error messages.
 * </p>
 */
@Data
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ErrorDTO {
	
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy HH:mm:ss")
	private LocalDateTime timestamp = LocalDateTime.now();
	
	private Integer status;
	
	private String error;   // Esempio: "Bad Request" o "Conflict"

	/**
	 * A general error message describing the issue. This message provides an
	 * overview of the error encountered during processing.
	 */
	private String message;
	
	/*The URL generated by the error*/
	private String path;

	/**
	 * A map of field-specific error messages. The key represents the field name and
	 * the value contains the corresponding error message related to that specific
	 * field.
	 */
	private Map<String, String> fieldErrors;

	public ErrorDTO(HttpStatus httpStatus, String message, String path) {
		super();
		this.status = httpStatus.value();
        this.error = httpStatus.getReasonPhrase();
		this.message = message;
		this.path = path;
	}

	public ErrorDTO(HttpStatus httpStatus, String message, String path, Map<String, String> fieldErrors) {
		//call the previous constructor to have everithing
		this(httpStatus, message, path);
		this.fieldErrors = fieldErrors;
	}

}
